<?php


namespace arls\xa;


use yii\db\Exception;

/**
 * Class TransactionException
 * @package arls\xa
 *
 * Represents an exception generated by an XA Transaction
 */
class TransactionException extends Exception {
}